project: 
  type: website

website: 
  title: "Revathy Venugopal"
  sidebar: 
    contents: 
      - about/index.qmd

format: 
  html: 
    theme: 
      light: flatly
      dark: darkly
    toc: true
execute: 
  freeze: auto
